-- Criando a tabela de pacientes
CREATE TABLE Pacientes (
    cpf VARCHAR2(15) PRIMARY KEY,
    nome VARCHAR2(50),
    data_nascimento DATE,
    sintomas VARCHAR2(100)
);

-- Criando a tabela de médicos
CREATE TABLE Medicos (
    crm VARCHAR2(15) PRIMARY KEY,
    nome VARCHAR2(50),
    especializacao VARCHAR2(50),
    disponibilidade CHAR(1) CHECK (disponibilidade IN ('Y', 'N')) -- 'Y' para disponível, 'N' para não disponível
);

-- Criando a tabela de consultas
CREATE TABLE Consultas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE,
    cpf_paciente VARCHAR2(15),
    crm_medico VARCHAR2(15),
    diagnostico VARCHAR2(100),
    FOREIGN KEY (cpf_paciente) REFERENCES Pacientes(cpf),
    FOREIGN KEY (crm_medico) REFERENCES Medicos(crm)
);